### ISSUE TITLE
Simplify usage with SendGrid as an Heroku Addon

### ISSUE THREAD

**Issue by hfjallemark** [luckyframework/carbon_sendgrid_adapter#1]
Send grid requires `SEND_GRID_KEY` by default but the Heroku addon adds the following config vars: `SENDGRID_PASSWORD` and `SENDGRID_USER` which requires me to manually add a KEY too. Not a high priority but would be nice if it could work out of the box with Heroku.

**Comment by jwoertink** [comment]
Yeah, that's a good idea. Thanks for the suggestion!

**Comment by ghost** [comment]
@jwoertink I'd like to work on this if no one has started yet 👍🏻

**Comment by jwoertink** [comment]
@Liberatys sure thing! That would be awesome.

**Comment by ghost** [comment]
https://docs.sendgrid.com/for-developers/sending-email/authentication#basic-authentication - 😆 I should have read the entire page before implementing it 😆 

> To ensure the security of your account, Twilio SendGrid has ended support for basic authentication with username and password as of Q4 2020.

**Comment by jwoertink** [comment]
oh LOL :rofl: Yup. I just saw that too. I left a comment, but it looks like the answer here is that it's probably not an issue. The Heroku addon has most likely been updated to fully support the new way... I'm leaning towards we just close this out. What do you think @Liberatys ?

**Comment by ghost** [comment]
@jwoertink sure thing 👍🏻 no point in supporting something that is deprecated by the 'vendor' 😆

**Comment by jwoertink** [comment]
Cool. Thanks for taking it on anyway! Still closes out the issue :grimacing:

@hfjallemark Sorry it took so long to get around to this. Hopefully it is easier with Heroku at this point :joy:
